from db.models import Import, Merchant, Category, Transaction
from sqlalchemy.orm import Session


def save_parsed_transactions(db: Session, file_name: str, file_hash: str, parsed_transactions: list[dict]) -> Import:
    """
    Saves the parsed transactions to the database.
    Returns the import object.
    """
    existing_import = db.query(Import).filter(Import.file_hash == file_hash).first()
    if existing_import:
        raise ValueError("This file was already imported")

    import_table_row = Import(file_name=file_name, file_hash=file_hash)
    db.add(import_table_row)
    db.commit()
    db.refresh(import_table_row) # we need this because the id is generated by the database after the commit and this 'brings back' the id into the python object

    for parsed_transaction in parsed_transactions:
        merchant_name = parsed_transaction["merchant_name"]
        category_name = parsed_transaction["category"]

        merchant_table_row = db.query(Merchant).filter(Merchant.name == merchant_name).first()
        if not merchant_table_row:
            merchant_table_row = Merchant(name=merchant_name)
            db.add(merchant_table_row)
            db.commit()
            db.refresh(merchant_table_row)

        category_table_row = db.query(Category).filter(Category.name == category_name).first()
        if not category_table_row:
            category_table_row = Category(name=category_name)
            db.add(category_table_row)
            db.commit()
            db.refresh(category_table_row)

        transaction_table_row = Transaction(
            import_id=import_table_row.id,
            merchant_id=merchant_table_row.id,
            category_id=category_table_row.id,
            transaction_date=parsed_transaction["transaction_date"],
            amount=parsed_transaction["amount"],
            currency=parsed_transaction["currency"],
            description_raw=merchant_name,
        )
        db.add(transaction_table_row)

    db.commit()

    return import_table_row